#ifndef EXCHANGEPARAMS_H
#define EXCHANGEPARAMS_H


#define VADC_START_BYTE 0xA3

enum _pc_get
{
    _LP_READ_EMPTY,
    _LP_RD_CH_SETTINGS,
    _LP_RD_DATE_TIME,
    _LP_RD_ACK,
    _LP_RD_GETLOG,
    _LP_RD_GETOSC,
    _LP_RD_CLR_LOG,
    _LP_RD_SET_MODE,
    _LP_RD_TEST_MV,
    _LP_RD_TEST_MURS,//MURS2
    _LP_RD_TEST_MC,  //MURS1
    _LP_RD_TEST_TERMINAL,
    _LP_RD_PUSK_LP,
    _LP_RD_RESET_INF,
    _LP_RD_VER_PO,
    _LP_RD_TEST_AK,
    _LP_RD_FACTORY_DEF,
    _LP_RD_CALIBR,
    _LP_RD_TEST_KANAL,
    _LP_RD_SOUND_SETT,
    _LP_RD_RANDOM_SETTINGS,
    _LP_RD_SEND_HF_DATA,
    _LP_RD_GETCOUNT_LOG,


    //******* ДФЗ
    _LP_RD_CONFIG_VIRT_ADC=0x20,
    _LP_RD_CALIBR_MDFZ_ADC,
    _LP_RD_WRITE_MDFZ_REG,
    //PC
    _LP_RD_GET_MDFZ_IZM,
    _LP_RD_GET_V4Z_STATE,
    _LP_RD_GET_HW_SETTINGS,
    _LP_RD_GET_TIME,
    _LP_RD_GET_DATE,
    _LP_RD_GET_LOG,
    _LP_RD_GET_LEDS,
    _LP_RD_GET_OSC_AK,
    _LP_RD_GET_MODULE_STATE,
    _LP_RD_GET_IZM,
    _LP_RD_GET_MODULES_FW,
    _LP_RD_GET_OMP,
    _LP_RD_GET_MU_HELTH,

    _LP_RD_VBUTTON = 0x30,
    _LP_RD_GET_STRING,
    _LP_RD_GET_GOOSE_STATE,
    _LP_RD_GETCOMPARATORS_STATE,
    _LP_RD_VADC_PARAM,

    _LP_RD_GET_FESTATE,

    _LP_RD_COUNT
};

enum _pc_rcv_ansv
{
    _LP_SET_EMPTY,
    _LP_SET_SETTINGS,
    _LP_SET_TIME,
    _LP_SET_DATE,
    _LP_SEND_AK_RES,
    _LP_SEND_RESET,
    _LP_SEND_EVENT,
    _LP_SEND_LOG,
    _LP_SEND_LEDSTATE,
    _LP_TRANSMIT,
    _LP_SEND_ACK,
    _LP_SEND_OSC,
    _LP_START_AK,
    _LP_SEND_PA,
    _LP_SEND_MODULES_STATE,
    _LP_SEND_IZM,
    _LP_GET_VER_PO,
    _LP_SEND_FW,
    _LP_SEND_CALIBR,
    _LP_SEND_TEST_KANAL,
    _LP_SEND_RANDOM_SETTINGS,
    _LP_SEND_FFT,
    _LP_SEND_PHASE,
    _LP_SEND_BUZZER,
    _LP_SEND_LOG_COUNT,
    _LP_SEND_MODULES_EXP_STATE,
    _LP_SEND_STRING,
    _LP_SEND_GOOSE_STATE,


    //ДФЗ
    _LP_SEND_V4Z_STATE = 0x20,
    _LP_SEND_V4Z_IZM,
    _LP_SEND_COMPARATORS_STATE,
    _LP_SEND_MDFZ_OSC,
    _LP_SEND_MDFZ_OMP,
    _LP_SEND_MU_HEALTH,
    _LP_SEND_MZ_STATE_REGS,
    _LP_SEND_VADC_PARAM,

    _LP_SEND_FESTATE,

    _LP_COM_COUNT
};

#endif // EXCHANGEPARAMS_H
